[package]
name = "dec04"
version = "0.1.0"
authors = ["Henry Wallace <henry@henrywallace.io>"]

[[bin]]
path = "src/main.rs"
name = "dec04"

[dependencies]
"clap" = "2.32.0"
"chrono" = "0.4.6"
"regex" = "1"
"lazy_static" = "1"
